name: Release Management

permissions:
  pull-requests: write
  id-token: write
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  # Create the Github Release™️ so the packages have something to be uploaded to
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: rust
          package-name: gbj11

  # Build and packages all the things
  upload-artifacts:
    needs: create-release
    if: ${{ needs.create-release.outputs.release_created }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
            lfs: 'true'
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - uses: jetli/trunk-action@v0.4.0
      # TODO: Separate build to its own action so it can be reused...
      - name: Run build
        run: |
          set -ex
          trunk build --release

          sed -i 's|/gbj|./gbj|g' dist/index.html

          touch dist/.nojekyll

          mv dist gbj-${{ needs.create-release.outputs.tag }}

          zip -r gbj-${{ needs.create-release.outputs.tag }}.zip gbj-${{ needs.create-release.outputs.tag }}

          gh release upload ${{ needs.create-release.outputs.tag }} gbj-${{ needs.create-release.outputs.tag }}.zip

          gh release edit ${{ needs.create-release.outputs.tag }} --draft=false

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: gbj-${{ needs.create-release.outputs.tag }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2